[package]
name = "golem-gpu-imager"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
directories = "6.0.0"
fatfs = "0.3.6"
#gpt-parser = "0.0.10"
iced = { git = "https://github.com/iced-rs/iced.git", features = ["canvas", "tokio", "svg", "image"] }
rs-drivelist = "0.9.4"

[build-dependencies]
windows_exe_info = {  version = "0.5", features = ["manifest", "versioninfo", "icon_ico"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[package.metadata.winres]
